substitutions:
   devicename: test-cam
 
esphome:
   name: ${devicename}
   platform: ESP32
   board: esp32dev
 
#Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

ota:
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5

web_server:
  port: 80
  auth:
    username: !secret esphome_web_username
    password: !secret esphome_web_password

wifi:
   ssid: !secret wifi_ssid
   password: !secret wifi_password

# Ai-Thinker Camera   
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  name: ${devicename} cam
 
 # Flashlight CHECK PIN
output:
   - platform: gpio
     pin: GPIO4
     id: gpio_4 

light:
  - platform: binary
    output: gpio_4
    name: ${devicename} light  


sensor:
  - platform: wifi_signal
    name: ${devicename} wifi signal
    update_interval: 600s
 
  - platform: uptime
    name: ${devicename} uptime 
